'use server';

import OpenAI from 'openai';

interface OpenAIGenerationResult {
    success: boolean;
    imageUrl?: string;
    prompt?: string;
    error?: string;
}

export async function generateImageWithOpenAI(prompt: string): Promise<OpenAIGenerationResult> {
    console.log('[OpenAI] Starting image generation with prompt:', prompt);

    try {
        // Check if API key is available
        const apiKey = process.env.OPENAI_API_KEY;
        if (!apiKey) {
            throw new Error('OPENAI_API_KEY is not configured');
        }

        // Initialize OpenAI
        const openai = new OpenAI({
            apiKey: apiKey,
        });

        // Enhanced prompt for better image generation
        const enhancedPrompt = `${prompt}, high resolution, detailed, professional quality, sharp focus, 4k, mobile wallpaper style, 9:16 aspect ratio, digital art`;

        console.log('[OpenAI] Sending request to OpenAI API...');

        // Generate image using OpenAI DALL-E
        const response = await openai.images.generate({
            model: "gpt-4o-mini",
            prompt: enhancedPrompt,
            n: 1,
            size: "1024x1792", // 9:16 aspect ratio for mobile wallpapers
            quality: "hd",
            style: "vivid",
        });

        if (!response.data || response.data.length === 0) {
            throw new Error('No image generated by OpenAI');
        }

        const imageUrl = response.data[0].url;
        if (!imageUrl) {
            throw new Error('No image URL in OpenAI response');
        }

        console.log('[OpenAI] Image generated successfully');

        return {
            success: true,
            imageUrl,
            prompt: enhancedPrompt
        };

    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        console.error(`[OpenAI] ERROR in generateImageWithOpenAI: ${errorMessage}`);

        return {
            success: false,
            error: `OpenAI image generation failed: ${errorMessage}`
        };
    }
}

export async function generateRandomImageWithOpenAI(): Promise<OpenAIGenerationResult> {
    const randomPrompts = [
        // === ANIME GIRLS (TOP REACH) ===
        "Vertical anime girl wallpaper, soft pastel lighting, close-up face, big expressive eyes, clean background, dreamy aesthetic, ultra-sharp focus, 4k",
        "Anime girl standing by rainy window at night, city lights bokeh, neon reflections, cozy mood, cinematic anime lighting, vertical phone wallpaper",
        "Cyberpunk anime girl under neon signs, purple and blue color palette, rain particles, glowing eyes, ultra-detailed anime illustration",
        "Anime girl looking at starry sky from rooftop, wind-blown hair, moonlight glow, minimal background, wallpaper composition",
        "Cute anime girl in oversized hoodie, soft lo-fi lighting, clean pastel background, aesthetic phone wallpaper",

        // === BEAUTIFUL WOMEN (MASS APPEAL) ===
        "Cinematic portrait of a beautiful woman, soft golden hour light, shallow depth of field, elegant pose, ultra HD wallpaper",
        "Moody aesthetic female portrait, side lighting, dark background, cinematic photography style, phone wallpaper crop",
        "Elegant woman with flowing hair, pastel tones, clean minimal background, high-fashion aesthetic wallpaper",
        "Neon-lit female portrait, cyberpunk lighting, pink and blue glow, cinematic mood, ultra-clear focus",

        // === JAPANESE CULTURE (HIGH SAVE RATE) ===
        "Japanese street at night, glowing paper lanterns, rain reflections, cinematic framing, vertical wallpaper",
        "Cherry blossom trees in full bloom, soft pink petals falling, blue sky, peaceful Japanese aesthetic",
        "Torii gate in misty forest, early morning fog, soft light rays, spiritual zen wallpaper",
        "Tokyo cyberpunk alley, neon kanji signs, rain-soaked street, ultra-detailed night wallpaper",

        // === CYBERPUNK / FUTURISTIC (DESKTOP FAVORITE) ===
        "Cyberpunk city skyline at night, neon skyscrapers, flying cars, purple-blue palette, ultra-wide wallpaper",
        "Rainy futuristic street, neon reflections, lone figure walking, cinematic sci-fi mood",
        "Futuristic megacity viewed from rooftop, glowing lights, dramatic clouds, epic scale wallpaper",

        // === COZY / LIFESTYLE (SAVE FARMER) ===
        "Cozy coffee cup by rainy window, warm lamp light, soft shadows, aesthetic phone wallpaper",
        "Late-night study desk, laptop glow, books, soft warm lighting, cozy aesthetic wallpaper",
        "Minimal bedroom at night, city lights outside window, calm cozy vibe, clean composition",

        // === SPACE / SKY (HIGH VISUAL IMPACT) ===
        "Astronaut floating in space, Earth glowing in background, cinematic lighting, ultra HD wallpaper",
        "Milky Way galaxy above mountain silhouette, long exposure style, night sky wallpaper",
        "Surreal planets aligned in colorful space, soft glow, minimal composition",

        // === ADVENTURE / FANTASY ===
        "Lone adventurer standing on cliff edge, massive fantasy landscape, epic scale, cinematic light",
        "Floating islands above clouds, golden sunset light, fantasy dreamscape wallpaper",
        "Magical bridge leading into glowing portal, surreal fantasy art, ultra-detailed",

        // === BEACH / HOLIDAY ===
        "Tropical beach at sunset, palm trees silhouette, golden sky, calm ocean, peaceful wallpaper",
        "Ocean waves crashing under pastel sunset sky, minimal beach aesthetic",
        "Coastal road with vintage car, summer holiday vibe, warm cinematic light",

        // === CITIES / CARS ===
        "Rainy city street at night, reflections on asphalt, cinematic photography wallpaper",
        "Luxury sports car parked under neon lights, cyberpunk city vibe, ultra HD",
        "Modern city skyline at blue hour, glowing windows, clean wallpaper composition",

        // === NATURE / FOREST ===
        "Misty forest with sun rays through trees, magical morning light, ultra-detailed nature wallpaper",
        "Autumn forest path covered in golden leaves, cozy nature aesthetic",
        "Mountain lake with perfect reflection, calm zen landscape wallpaper",

        // === BIRDS / SKY ELEMENTS ===
        "Birds flying across dramatic sunset sky, silhouette composition, minimal wallpaper",
        "Eagle soaring above mountains, cinematic wildlife photography style",

        // === ABSTRACT / CREATIVE ===
        "Smooth abstract waves in pastel colors, soft gradients, modern aesthetic wallpaper",
        "Minimal geometric abstract design, neon glow accents, dark background",
        "Surreal abstract shapes floating in soft light, ultra HD digital art",

        // === PAINTING STYLE ===
        "Oil painting style fantasy landscape, rich brush strokes, warm colors",
        "Impressionist city street painting at night, glowing lights",

        // === QUOTE BACKGROUNDS (UTILITY CONTENT) ===
        "Minimal pastel gradient background with soft light for quote wallpaper",
        "Calm sky with subtle clouds, empty center space for inspirational quote",
        "Nature-inspired minimal wallpaper designed for daily motivation text"
    ];


    const randomPrompt = randomPrompts[Math.floor(Math.random() * randomPrompts.length)];
    return generateImageWithOpenAI(randomPrompt);
} 
